baseURL = '/'
languageCode = 'fr'
defaultContentLanguage = "fr"
hasCJKLanguage = true
enableEmoji = true
title = 'Fehlmann.dev'
copyright = 'Fehlmann Dylan'
theme = 'hugo-theme-itheme'
paginate = 5
[params]
  defaultCover = 'https://www.apple.com.cn/newsroom/images/apple-logo_black.jpg.landing-regular_2x.jpg'
  email = 'dylan@fehlmann.dev'
  [[params.socialMedia]]
    name = 'Github'
    url = 'https://github.com/fehlmanndy'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true