ame: hugo2infomaniak

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true 

      - name: Build
        run: hugo --minify

      - name: Install git-ftp
        run: sudo apt-get install git-ftp

      - name: Deploy with git-ftp
        run: |
          git ftp init --user "${{ secrets.SFTP_USER }}" \
                       --passwd "${{ secrets.SFTP_PASSWORD }}" \
                       ftp://${{ secrets.SFTP_SERVER }}
