name: hugo2infomaniak

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true 

      - name: Build Hugo site
        run: hugo --minify  # Assure-toi que le site est généré dans le dossier public/

      - name: List files in public directory  # Vérification des fichiers générés
        run: ls -la public/

      - name: Install lftp
        run: sudo apt-get install lftp

      - name: Deploy with lftp
        run: |
          lftp -e "mirror -R public/ /path/on/server --ignore-time --parallel=2; quit" -u ${{ secrets.SFTP_USER }},${{ secrets.SFTP_PASSWORD }} ${{ secrets.SFTP_SERVER }}
